CREATE TABLE `cherchercovoit` (
  `NUMERODEMANDE` int(5) NOT NULL,
  `MATRICULE` int(5) NOT NULL,
  `IDENTIFIANTLIEU` char(32) COLLATE utf8_unicode_ci NOT NULL,
  `IDENTIFIANTLIEU_ARRIVEE` char(32) COLLATE utf8_unicode_ci NOT NULL,
  `DATEDEPART` date NOT NULL,
  PRIMARY KEY (`NUMERODEMANDE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
